import Foundation
import CoreLocation

extension SkateShop {

    /// 10 real Bay Area skate shops, pinned to the map as permanent annotations.
    static let bayArea: [SkateShop] = [
        SkateShop(
            id: UUID(),
            name: "510 Skateboarding",
            address: "2506 Telegraph Ave, Berkeley, CA",
            neighborhood: "Berkeley",
            coordinate: CLLocationCoordinate2D(latitude: 37.8561, longitude: -122.2596),
            distanceText: "12 mi",
            rating: 4.9,
            isOpen: true,
            specialty: "Independent & small-batch decks",
            accentColorHex: "#FF9500",
            featuredChallenge: "The Telegraph Weave",
            phone: "(510) 843-1863",
            website: "https://510skateboarding.com",
            owners: "Jerry & Dandy"
        ),
        SkateShop(
            id: UUID(),
            name: "Atlas Skateboard Store",
            address: "209 2nd Ave, San Mateo, CA",
            neighborhood: "San Mateo",
            coordinate: CLLocationCoordinate2D(latitude: 37.5634, longitude: -122.3231),
            distanceText: "20 mi",
            rating: 4.7,
            isOpen: true,
            specialty: "Street & Park",
            accentColorHex: "#C77DFF",
            featuredChallenge: "The Caltrain Gap",
            phone: "(650) 401-7110",
            website: "https://atlasskateboarding.com",
            owners: nil
        ),
        SkateShop(
            id: UUID(),
            name: "Break Free SkateShop",
            address: "1212 Webster St, Oakland, CA",
            neighborhood: "Downtown Oakland",
            coordinate: CLLocationCoordinate2D(latitude: 37.8039, longitude: -122.2718),
            distanceText: "9 mi",
            rating: 4.8,
            isOpen: true,
            specialty: "Community shop & rentals",
            accentColorHex: "#3AB5E6",
            featuredChallenge: "The Webster Ledge",
            phone: "(510) 817-4450",
            website: "https://breakfreeskateshop.com",
            owners: nil
        ),
        SkateShop(
            id: UUID(),
            name: "Deluxe Skateshop / DLX",
            address: "2330 Mission St, San Francisco, CA",
            neighborhood: "Mission District",
            coordinate: CLLocationCoordinate2D(latitude: 37.7568, longitude: -122.4185),
            distanceText: "0.5 mi",
            rating: 4.9,
            isOpen: true,
            specialty: "Hard goods & premium decks",
            accentColorHex: "#FF5A35",
            featuredChallenge: "The Mission Drop",
            phone: "(415) 626-5588",
            website: "https://www.dlxskateshop.com",
            owners: nil
        ),
        SkateShop(
            id: UUID(),
            name: "Everyday Skate Shop",
            address: "10 Geary St, San Francisco, CA",
            neighborhood: "Union Square",
            coordinate: CLLocationCoordinate2D(latitude: 37.7877, longitude: -122.4064),
            distanceText: "1.2 mi",
            rating: 4.6,
            isOpen: true,
            specialty: "Apparel & lifestyle",
            accentColorHex: "#CCFF40",
            featuredChallenge: "The Union Square Manual",
            phone: "(415) 728-4620",
            website: "https://www.everydaysfc.com",
            owners: nil
        ),
        SkateShop(
            id: UUID(),
            name: "FTC Skateboarding",
            address: "1632 Haight St, San Francisco, CA",
            neighborhood: "Haight-Ashbury",
            coordinate: CLLocationCoordinate2D(latitude: 37.7693, longitude: -122.4536),
            distanceText: "2.8 mi",
            rating: 4.9,
            isOpen: true,
            specialty: "SF street culture staple",
            accentColorHex: "#FFD60A",
            featuredChallenge: "The Haight Kickflip",
            phone: "(415) 626-0663",
            website: "https://ftcsf.com",
            owners: nil
        ),
        SkateShop(
            id: UUID(),
            name: "Mission Skateboards",
            address: "3045 24th St, San Francisco, CA",
            neighborhood: "Mission District",
            coordinate: CLLocationCoordinate2D(latitude: 37.7524, longitude: -122.4150),
            distanceText: "1.5 mi",
            rating: 4.7,
            isOpen: true,
            specialty: "Beginner-friendly & local crews",
            accentColorHex: "#0ADFB4",
            featuredChallenge: "The 24th Street Session",
            phone: "(415) 647-7888",
            website: "https://missionsk8shop.com",
            owners: nil
        ),
        SkateShop(
            id: UUID(),
            name: "Orbit Skate & Boutique",
            address: "15206 E 14th St, San Leandro, CA",
            neighborhood: "San Leandro",
            coordinate: CLLocationCoordinate2D(latitude: 37.7229, longitude: -122.1423),
            distanceText: "16 mi",
            rating: 4.8,
            isOpen: true,
            specialty: "Skates & boutique apparel",
            accentColorHex: "#FF2D55",
            featuredChallenge: "The East Bay Grind",
            phone: "(510) 317-9907",
            website: "https://orbitskates.com",
            owners: nil
        ),
        SkateShop(
            id: UUID(),
            name: "Pacifica Board Factory",
            address: "1117 Palmetto Ave, Pacifica, CA",
            neighborhood: "Pacifica",
            coordinate: CLLocationCoordinate2D(latitude: 37.6138, longitude: -122.4875),
            distanceText: "12 mi",
            rating: 4.7,
            isOpen: true,
            specialty: "Custom decks & oceanside gear",
            accentColorHex: "#30D158",
            featuredChallenge: "The Coastline Cruise",
            phone: "(650) 550-0676",
            website: "https://pacificaboardfactory.com",
            owners: nil
        ),
        SkateShop(
            id: UUID(),
            name: "Skatevirus Skateshop",
            address: "565 Tully Rd, San Jose, CA",
            neighborhood: "San Jose",
            coordinate: CLLocationCoordinate2D(latitude: 37.3100, longitude: -121.8612),
            distanceText: "48 mi",
            rating: 4.8,
            isOpen: true,
            specialty: "South Bay street scene",
            accentColorHex: "#FF6B35",
            featuredChallenge: "The South Bay Slide",
            phone: "(408) 964-8640",
            website: "https://skatevirus.com",
            owners: nil
        )
    ]
}
