import Foundation
import CoreLocation

// MARK: - Fresno / 559 Skate Spots
// Sources: findskatespots.com, @559streetspots, local knowledge (Sept 2026)

extension SKMockData {

    static let fresnoSpots: [SkateSpot] = [

        // ── DOWNTOWN FRESNO ───────────────────────────────────────────────────

        SkateSpot(id: UUID(),
                  name: "Fresno City Hall Plaza",
                  neighborhood: "Downtown Fresno",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7358, longitude: -119.7870),
                  difficulty: .intermediate,
                  terrainTags: ["Marble Ledge", "Stairs", "Handicap Rail"],
                  popularity: 88,
                  featuredTrick: "Noseslide"),

        SkateSpot(id: UUID(),
                  name: "Chukchansi Park Steps",
                  neighborhood: "Downtown Fresno",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7370, longitude: -119.7881),
                  difficulty: .advanced,
                  terrainTags: ["Stairs", "Marble Gap", "Rail"],
                  popularity: 91,
                  featuredTrick: "Kickflip"),

        SkateSpot(id: UUID(),
                  name: "Fresno Convention Center Ledge",
                  neighborhood: "Downtown Fresno",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7344, longitude: -119.7885),
                  difficulty: .intermediate,
                  terrainTags: ["Ledge", "Stairs", "Flat"],
                  popularity: 79,
                  featuredTrick: "50-50"),

        SkateSpot(id: UUID(),
                  name: "County Hall of Records Marble",
                  neighborhood: "Downtown Fresno",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7368, longitude: -119.7867),
                  difficulty: .beginner,
                  terrainTags: ["Marble Ledge", "Manual Pad"],
                  popularity: 65,
                  featuredTrick: "Boardslide"),

        SkateSpot(id: UUID(),
                  name: "Fulton Mall Ledge Line",
                  neighborhood: "Downtown Fresno",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7375, longitude: -119.7921),
                  difficulty: .intermediate,
                  terrainTags: ["Concrete Ledge", "Curb", "Flat"],
                  popularity: 83,
                  featuredTrick: "Crooks"),

        SkateSpot(id: UUID(),
                  name: "Federal Building Stairs",
                  neighborhood: "Downtown Fresno",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7359, longitude: -119.7895),
                  difficulty: .pro,
                  terrainTags: ["12-Stair", "Handrail", "Gap"],
                  popularity: 86,
                  featuredTrick: "Heelflip"),

        SkateSpot(id: UUID(),
                  name: "Bitwise South Stadium Plaza",
                  neighborhood: "Downtown Fresno",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7340, longitude: -119.7905),
                  difficulty: .beginner,
                  terrainTags: ["Fresh Concrete", "Curb", "Manual Pad"],
                  popularity: 58,
                  featuredTrick: "Manual"),

        SkateSpot(id: UUID(),
                  name: "Fresno Water Tower Manual Pad",
                  neighborhood: "Malt District",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7481, longitude: -119.7820),
                  difficulty: .beginner,
                  terrainTags: ["Manual Pad", "Flat"],
                  popularity: 61,
                  featuredTrick: "Nose Manual"),

        SkateSpot(id: UUID(),
                  name: "Poverello House Curb Cut",
                  neighborhood: "Downtown Fresno",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7419, longitude: -119.7899),
                  difficulty: .beginner,
                  terrainTags: ["Curb", "Banks"],
                  popularity: 52,
                  featuredTrick: "Ollie"),

        // ── TOWER DISTRICT / CENTRAL ──────────────────────────────────────────

        SkateSpot(id: UUID(),
                  name: "Tower District Wishon Gap",
                  neighborhood: "Tower District",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7698, longitude: -119.8005),
                  difficulty: .intermediate,
                  terrainTags: ["Gap", "Manual Pad", "Curb"],
                  popularity: 76,
                  featuredTrick: "Fs Flip"),

        SkateSpot(id: UUID(),
                  name: "Fresno Art Museum Banks",
                  neighborhood: "Tower District",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7700, longitude: -119.7981),
                  difficulty: .intermediate,
                  terrainTags: ["Concrete Banks", "Ledge"],
                  popularity: 71,
                  featuredTrick: "Frontside Ollie"),

        SkateSpot(id: UUID(),
                  name: "Roeding Park Concrete Paths",
                  neighborhood: "Roeding Park",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7570, longitude: -119.8142),
                  difficulty: .beginner,
                  terrainTags: ["Smooth Path", "Banks", "Curb"],
                  popularity: 60,
                  featuredTrick: "Carve"),

        SkateSpot(id: UUID(),
                  name: "Fresno City College Steps",
                  neighborhood: "Central Fresno",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7463, longitude: -119.7789),
                  difficulty: .intermediate,
                  terrainTags: ["Stairs", "Waxed Ledge", "Rail"],
                  popularity: 74,
                  featuredTrick: "Switch Crooks"),

        // ── NORTH FRESNO ──────────────────────────────────────────────────────

        SkateSpot(id: UUID(),
                  name: "CSU Fresno Library Ledges",
                  neighborhood: "Fresno State",
                  coordinate: CLLocationCoordinate2D(latitude: 36.8120, longitude: -119.7449),
                  difficulty: .intermediate,
                  terrainTags: ["Marble Ledge", "Stairs", "Brick"],
                  popularity: 82,
                  featuredTrick: "Bluntslide"),

        SkateSpot(id: UUID(),
                  name: "Save Mart Center Steps",
                  neighborhood: "Fresno State",
                  coordinate: CLLocationCoordinate2D(latitude: 36.8136, longitude: -119.7468),
                  difficulty: .advanced,
                  terrainTags: ["Wide Stairs", "Gap", "Handrail"],
                  popularity: 77,
                  featuredTrick: "Ollie North"),

        SkateSpot(id: UUID(),
                  name: "Fashion Fair Hubba",
                  neighborhood: "North Fresno",
                  coordinate: CLLocationCoordinate2D(latitude: 36.8137, longitude: -119.7902),
                  difficulty: .advanced,
                  terrainTags: ["Hubba Ledge", "Stairs"],
                  popularity: 85,
                  featuredTrick: "Backside Nosegrind"),

        SkateSpot(id: UUID(),
                  name: "Fig Garden Village Manual Pad",
                  neighborhood: "Fig Garden",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7892, longitude: -119.8153),
                  difficulty: .beginner,
                  terrainTags: ["Manual Pad", "Smooth Concrete"],
                  popularity: 55,
                  featuredTrick: "Manual"),

        SkateSpot(id: UUID(),
                  name: "River Park Concrete Banks",
                  neighborhood: "River Park",
                  coordinate: CLLocationCoordinate2D(latitude: 36.8369, longitude: -119.7735),
                  difficulty: .intermediate,
                  terrainTags: ["Banks", "Ledge", "Curb"],
                  popularity: 69,
                  featuredTrick: "Frontside Grind"),

        SkateSpot(id: UUID(),
                  name: "Woodward Park Amphitheater Ledge",
                  neighborhood: "Woodward Park",
                  coordinate: CLLocationCoordinate2D(latitude: 36.8393, longitude: -119.8213),
                  difficulty: .beginner,
                  terrainTags: ["Low Ledge", "Smooth Path", "Banks"],
                  popularity: 62,
                  featuredTrick: "50-50"),

        SkateSpot(id: UUID(),
                  name: "Manchester Center Curb Line",
                  neighborhood: "Manchester",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7818, longitude: -119.7982),
                  difficulty: .beginner,
                  terrainTags: ["Curb", "Flat", "Manual Pad"],
                  popularity: 50,
                  featuredTrick: "Kickflip"),

        SkateSpot(id: UUID(),
                  name: "North Fresno Long Hubba",
                  neighborhood: "North Fresno",
                  coordinate: CLLocationCoordinate2D(latitude: 36.8600, longitude: -119.8234),
                  difficulty: .pro,
                  terrainTags: ["Long Hubba", "Stairs", "Downhill"],
                  popularity: 80,
                  featuredTrick: "Lipslide"),

        // ── EAST / SOUTH FRESNO ───────────────────────────────────────────────

        SkateSpot(id: UUID(),
                  name: "Fresno Pacific University Brick Ledge",
                  neighborhood: "Southeast Fresno",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7299, longitude: -119.7503),
                  difficulty: .intermediate,
                  terrainTags: ["Brick Ledge", "Gap", "Flat"],
                  popularity: 64,
                  featuredTrick: "Smith Grind"),

        SkateSpot(id: UUID(),
                  name: "Kings Canyon Manual Pad",
                  neighborhood: "East Fresno",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7340, longitude: -119.7497),
                  difficulty: .beginner,
                  terrainTags: ["Manual Pad", "Curb"],
                  popularity: 57,
                  featuredTrick: "Nose Manual"),

        SkateSpot(id: UUID(),
                  name: "Sunnyside Schoolyard Banks",
                  neighborhood: "Sunnyside",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7287, longitude: -119.7384),
                  difficulty: .beginner,
                  terrainTags: ["Banks", "Smooth Blacktop", "Curb"],
                  popularity: 48,
                  featuredTrick: "Carve"),

        SkateSpot(id: UUID(),
                  name: "Calwa DIY Bank",
                  neighborhood: "Calwa",
                  coordinate: CLLocationCoordinate2D(latitude: 36.7198, longitude: -119.7701),
                  difficulty: .intermediate,
                  terrainTags: ["DIY Bank", "Concrete Wall", "Rough"],
                  popularity: 66,
                  featuredTrick: "Rock to Fakie"),
    ]
}
